# Generated by Django 4.2.4 on 2023-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberregistration',
            old_name='national_codes',
            new_name='national_code',
        ),
        migrations.RenameField(
            model_name='memberregistration',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='last_names',
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='first_name_last_name',
            field=models.CharField(default='w2', max_length=200),
            preserve_default=False,
        ),
    ]
