# Generated by Django 4.2.4 on 2023-08-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_rename_national_codes_memberregistration_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberregistration',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='phone_number',
        ),
    ]
